Build for mobile

diff --git a/build_tba_alpha b/build_tba_alpha
--- a/build_tba_alpha
+++ b/build_tba_alpha
@@ -255,6 +255,18 @@ checkout_torbrowser_tag() {
     popd
 }
 
+mach_artifact() {
+    # Yes, it assumes we're in .mozbuild
+    pushd .mozbuild
+    ../tor-browser/mach artifact toolchain --from-build linux64-clang
+    save=$?
+    if [ ! $? = 0 ]; then
+        echo "mach bootstrap artifact failed."
+    fi
+    popd
+    return $save
+}
+
 mach_bootstrap() {
     if [ -n "${MOZ_FORCE_BOOTSTRAP}" ]; then
         # Fallthrough
@@ -266,13 +278,34 @@ mach_bootstrap() {
         echo "Okay, let's run bootstrap"
     fi
     pushd tor-browser
-    ./mach bootstrap --no-interactive
+    ./mach bootstrap --no-interactive --application-choice mobile_android
+    save=$?
+    if [ ! $? = 0 ]; then
+        echo "mach bootstrap failed."
+	popd
+	return $save
+    fi
+
+    popd
 
     . `pwd`/.cargo/env
     rustup target add armv7-linux-androideabi
-
     save=$?
-    popd
+    if [ ! $? = 0 ]; then
+        echo "rustup failed."
+    elif [ -n "${MOZ_NO_LOOP_BOOTSTRAP}" ]; then
+	    echo "Bootstrapping complete"
+    else
+	    # Let's run it again, so we can finishin bootstrapping rust
+	    export MOZ_FORCE_BOOTSTRAP=1
+	    export MOZ_NO_LOOP_BOOTSTRAP=1
+	    mach_bootstrap
+            if [ ! $? = 0 ]; then
+                return $?
+            fi
+	    mach_artifact
+	    save=$?
+    fi
     return $save
 }
 
@@ -304,8 +337,8 @@ build_https_everywhere() {
     XPI_NAME="$1"
     pushd https-everywhere
     #git clean -fdx
-    #./install-dev-dependencies.sh
-    #./make.sh
+    #./install-dev-dependencies.sh --no-prompt
+    #./make.sh  "${HTTPS_EVERYWHERE_GIT_TAG}"
     save=0
     if [ ! -f "pkg/${XPI_NAME}" ]; then
         echo "https-everywhere has many dependencies. Please build it yourself (or download it and place it in `pwd`/pkg/${XPI_NAME})"
